require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'
    - 'vendor/ruby/**/*'
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'
  IgnoredPatterns:
    - '^#*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  Exclude:
    - 'lib/**/spandx/**/**'

Style/RedundantFreeze:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: 'single_quotes'

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 80

RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/unit/core/dependency_spec.rb'

RSpec/NamedSubject:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/RedundantPredicateMatcher:
  Exclude:
    - 'spec/unit/dotnet/parsers/csproj_spec.rb'
    - 'spec/unit/dotnet/parsers/packages_config_spec.rb'
    - 'spec/unit/dotnet/parsers/sln_spec.rb'
    - 'spec/unit/java/parsers/maven_spec.rb'
    - 'spec/unit/js/parsers/npm_spec.rb'
    - 'spec/unit/js/parsers/yarn_spec.rb'
    - 'spec/unit/os/parsers/apk_spec.rb'
    - 'spec/unit/os/parsers/dpkg_spec.rb'
    - 'spec/unit/php/parsers/composer_spec.rb'
    - 'spec/unit/python/parsers/pipfile_lock_spec.rb'
    - 'spec/unit/ruby/parsers/gemfile_lock_spec.rb'
    - 'spec/unit/terraform/parsers/lock_file_spec.rb'

RSpec/SpecFilePathFormat:
  Enabled: false
