#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
require "#{lib_path}/spandx"

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Spandx::SpandxCli.start
rescue Spandx::SpandxCli::Error => error
  puts "ERROR: #{error.message}"
  exit 1
end
