#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::parser::Parser;
    use crate::parsers::{NpmParser, YarnParser};
    use camino::Utf8PathBuf;
    use std::fs;
    use tempfile::tempdir;

    #[tokio::test]
    async fn test_npm_parser_can_parse() {
        let parser = NpmParser::new();
        
        assert!(parser.can_parse(Utf8PathBuf::from("/path/to/package-lock.json").as_path()));
        assert!(!parser.can_parse(Utf8PathBuf::from("/path/to/yarn.lock").as_path()));
        assert!(!parser.can_parse(Utf8PathBuf::from("/path/to/package.json").as_path()));
    }

    #[tokio::test]
    async fn test_npm_parser_parse_basic() {
        let content = r#"{
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 1,
            "requires": true,
            "dependencies": {
                "express": {
                    "version": "4.17.1",
                    "resolved": "https://registry.npmjs.org/express/-/express-4.17.1.tgz",
                    "integrity": "sha512-mHJ9O79RqluphRrcw2X/GTh3k9tVv8YcoyY4Kkh4WDMUYKRZUq0h1o0w2rrrxBqM7VoeUVqgb27xlEMXTnYt4g==",
                    "requires": {
                        "accepts": "~1.3.7",
                        "array-flatten": "1.1.1"
                    }
                },
                "lodash": {
                    "version": "4.17.21",
                    "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
                    "integrity": "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==",
                    "dev": true
                }
            }
        }"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("package-lock.json");
        fs::write(&file_path, content).unwrap();
        
        let parser = NpmParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        assert_eq!(result.len(), 2);
        
        let express = result.iter()
            .find(|dep| dep.name == "express")
            .expect("Express dependency not found");
        assert_eq!(express.version, "4.17.1");
        assert_eq!(express.metadata.get("resolved"), Some(&"https://registry.npmjs.org/express/-/express-4.17.1.tgz".to_string()));
        
        let lodash = result.iter()
            .find(|dep| dep.name == "lodash")
            .expect("Lodash dependency not found");
        assert_eq!(lodash.version, "4.17.21");
        assert_eq!(lodash.metadata.get("dev"), Some(&"true".to_string()));
    }

    #[tokio::test]
    async fn test_yarn_parser_can_parse() {
        let parser = YarnParser::new();
        
        assert!(parser.can_parse(Utf8PathBuf::from("/path/to/yarn.lock").as_path()));
        assert!(!parser.can_parse(Utf8PathBuf::from("/path/to/package-lock.json").as_path()));
        assert!(!parser.can_parse(Utf8PathBuf::from("/path/to/package.json").as_path()));
    }

    #[tokio::test]
    async fn test_yarn_parser_parse_basic() {
        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/core@^7.8.4":
  version "7.8.4"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.8.4.tgz#d496799e5c12195b3602d0fddd77294e3e38e80e"
  integrity sha512-0LiLrB2PwrVI+a2/IEskBopDYSd8BCb3rOvH7D5tzoWd696TBEduBvuLVm4Nx6rltrLZqvI3MCalB2K2aVzQjA==
  dependencies:
    "@babel/code-frame" "^7.8.3"
    "@babel/generator" "^7.8.4"

lodash@^4.17.13:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==

"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("yarn.lock");
        fs::write(&file_path, content).unwrap();
        
        let parser = YarnParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        assert_eq!(result.len(), 2);
        
        let babel_core = result.iter()
            .find(|dep| dep.name == "@babel/core")
            .expect("@babel/core dependency not found");
        assert_eq!(babel_core.version, "7.8.4");
        assert_eq!(babel_core.metadata.get("resolved"), Some(&"https://registry.yarnpkg.com/@babel/core/-/core-7.8.4.tgz#d496799e5c12195b3602d0fddd77294e3e38e80e".to_string()));
        
        let lodash = result.iter()
            .find(|dep| dep.name == "lodash")
            .expect("Lodash dependency not found");
        assert_eq!(lodash.version, "4.17.21");
        assert_eq!(lodash.metadata.get("integrity"), Some(&"sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==".to_string()));
    }

    #[tokio::test]
    async fn test_yarn_parser_with_quoted_names() {
        let content = r#"# yarn lockfile v1

"@types/node@^14.0.0":
  version "14.18.63"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-14.18.63.tgz"
  integrity sha512-fAtCfv4jJg+ExtXhvCkCqUKZ+4ok/JQk01qDKhL5BDDoS3AxKXhV5/MAVUZyQnSEd2GT92fkgZl0pz0Q0AzcIQ==

"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("yarn.lock");
        fs::write(&file_path, content).unwrap();
        
        let parser = YarnParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        assert_eq!(result.len(), 1);
        
        let types_node = result.iter()
            .find(|dep| dep.name == "@types/node")
            .expect("@types/node dependency not found");
        assert_eq!(types_node.version, "14.18.63");
    }

    #[tokio::test]
    async fn test_yarn_parser_empty_dependencies() {
        let content = r#"# yarn lockfile v1

"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("yarn.lock");
        fs::write(&file_path, content).unwrap();
        
        let parser = YarnParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        assert_eq!(result.len(), 0);
    }

    #[tokio::test]
    async fn test_npm_parser_empty_dependencies() {
        let content = r#"{
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 1,
            "requires": true,
            "dependencies": {}
        }"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("package-lock.json");
        fs::write(&file_path, content).unwrap();
        
        let parser = NpmParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        assert_eq!(result.len(), 0);
    }

    #[tokio::test]
    async fn test_npm_parser_missing_version() {
        let content = r#"{
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 1,
            "requires": true,
            "dependencies": {
                "express": {
                    "resolved": "https://registry.npmjs.org/express/-/express-4.17.1.tgz"
                },
                "lodash": {
                    "version": "4.17.21",
                    "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
                }
            }
        }"#;

        let temp_dir = tempdir().unwrap();
        let file_path = temp_dir.path().join("package-lock.json");
        fs::write(&file_path, content).unwrap();
        
        let parser = NpmParser::new();
        let path = Utf8PathBuf::from_path_buf(file_path).unwrap();
        let result = parser.parse(&path).await.unwrap();
        
        // Should only include lodash, not express (missing version)
        assert_eq!(result.len(), 1);
        
        let lodash = result.iter()
            .find(|dep| dep.name == "lodash")
            .expect("Lodash dependency not found");
        assert_eq!(lodash.version, "4.17.21");
    }
}